drop table if exists "destinacao_hospedagem";
create table "destinacao_hospedagem" (
  "id" bigint not null generated by default as identity,
  "descricao" varchar(64) not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "destinacao_hospedagem_un01"
    unique ("descricao")
)
engine InnoDB
auto_increment 13
default charset latin1;
drop table if exists "encaminhador";
create table "encaminhador" (
  "id" bigint not null generated by default as identity,
  "cargo" varchar(64) not null,
  "email" varchar(64) default null,
  "nome" varchar(64) not null,
  "telefone" varchar(16) default null,
  "entidade_id" bigint not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  "ativo" varchar(1) not null,
  primary key ("id")
)
engine InnoDB
auto_increment 146
default charset latin1;
drop table if exists "endereco";
create table "endereco" (
  "id" bigint not null generated by default as identity,
  "bairro" varchar(32) default null,
  "cep" varchar(9) default null,
  "cidade" varchar(64) not null,
  "complemento" varchar(32) default null,
  "latitude" double not null,
  "logradouro" varchar(64) not null,
  "longitude" double not null,
  "numero" int default null,
  "uf" varchar(2) not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id")
)
engine InnoDB
auto_increment 2889
default charset latin1;
drop table if exists "entidade";
create table "entidade" (
  "id" bigint not null generated by default as identity,
  "cnpj" varchar(14) not null,
  "email" varchar(64) default null,
  "nome" varchar(64) not null,
  "telefone" varchar(16) default null,
  "endereco_id" bigint not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  "observacoes" clob default null,
  "telefone2" varchar(16) default null,
  primary key ("id"),
  constraint "FKtkqsbybf0x0mygx1ps6cmc37w"
    foreign key ("endereco_id")
    references "endereco" ("id")
)
engine InnoDB
auto_increment 50
default charset latin1;
drop table if exists "estado_leito";
create table "estado_leito" (
  "id" bigint not null generated by default as identity,
  "descricao" varchar(32) not null,
  "disponivel" varchar(1) default null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id")
)
engine InnoDB
auto_increment 4
default charset latin1;
drop table if exists "hibernate_sequence";
create table "hibernate_sequence" (
  "next_val" bigint default null
)
engine InnoDB
default charset latin1;
drop table if exists "hospedagem";
create table "hospedagem" (
  "id" bigint not null generated by default as identity,
  "data_efetiva_saida" date default null,
  "data_entrada" date not null,
  "data_prevista_saida" date not null,
  "observacoes" clob default null,
  "tipo_utilizacao" varchar(1) not null,
  "destinacao_hospedagem_id" bigint not null,
  "encaminhador_id" bigint default null,
  "entidade_id" bigint default null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "hospedagem_fk01"
    foreign key ("encaminhador_id")
    references "encaminhador" ("id"),
  constraint "hospedagem_fk02"
    foreign key ("destinacao_hospedagem_id")
    references "destinacao_hospedagem" ("id"),
  constraint "hospedagem_fk03"
    foreign key ("entidade_id")
    references "entidade" ("id")
)
engine InnoDB
auto_increment 3798
default charset latin1;
drop table if exists "hospedagem_mock";
create table "hospedagem_mock" (
  "id" bigint not null generated by default as identity,
  "data_efetiva_saida" date default null,
  "data_entrada" date not null,
  "data_prevista_saida" date default null,
  "quarto" int default null,
  "situacao" varchar(1) not null,
  "dataEfetivaSaida" date default null,
  "dataEntrada" date default null,
  "dataPrevistaSaida" date default null,
  primary key ("id")
)
engine InnoDB
default charset latin1;
drop table if exists "hospedagem_tipo_servico";
create table "hospedagem_tipo_servico" (
  "id" bigint not null generated by default as identity,
  "hospedagem_id" bigint not null,
  "tipo_servico_id" bigint not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id")
)
engine InnoDB
auto_increment 3874
default charset latin1;
drop table if exists "hospede";
create table "hospede" (
  "id" bigint not null generated by default as identity,
  "hospedagem_id" bigint not null,
  "pessoa_id" bigint not null,
  "tipo_hospede_id" bigint not null,
  "baixado" varchar(1) default null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id")
)
engine InnoDB
auto_increment 5624
default charset latin1;
drop table if exists "hospede_leito";
create table "hospede_leito" (
  "id" bigint not null generated by default as identity,
  "data_entrada" date not null,
  "hospede_id" bigint not null,
  "leito_id" bigint not null,
  "quarto_id" bigint not null,
  "data_saida" date default null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id")
)
engine InnoDB
auto_increment 3598
default charset latin1;
drop table if exists "leito";
create table "leito" (
  "id" bigint not null generated by default as identity,
  "numero" int not null,
  "quarto_id" bigint not null,
  "situacao_leito_id" bigint not null,
  "tipo_leito_id" bigint not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "leito_un01"
    unique ("quarto_id", "numero")
)
engine InnoDB
auto_increment 50
default charset latin1;
drop table if exists "pessoa";
create table "pessoa" (
  "id" bigint not null generated by default as identity,
  "cpf" varchar(11) default null,
  "data_nascimento" date not null,
  "email" varchar(64) default null,
  "estado_civil" varchar(1) default null,
  "nome" varchar(64) not null,
  "observacoes" clob default null,
  "rg" varchar(32) default null,
  "sexo" varchar(1) default null,
  "telefone" varchar(16) default null,
  "endereco_id" bigint not null,
  "updated_at" timestamp default null,
  "created_at" timestamp default null,
  "updated_by" bigint default null,
  "cartao_sus" varchar(16) default null,
  "created_by" bigint default null,
  "nacionalidade" varchar(64) default null,
  "profissao" varchar(64) default null,
  "telefone2" varchar(16) default null,
  "naturalidade_cidade" varchar(64) default null,
  "naturalidade_uf" varchar(2) default null,
  primary key ("id")
)
engine InnoDB
auto_increment 2659
default charset latin1;
drop table if exists "planilha_estadia";
create table "planilha_estadia" (
  "id" bigint not null generated by default as identity,
  "codigo" varchar(16) default null,
  "cpf" varchar(16) default null,
  "dataEntrada" date default null,
  "dataExpectativaSaida" date default null,
  "dataSaida" date default null,
  "observacoes" clob default null,
  "data_entrada" date default null,
  "data_expectativa_saida" date default null,
  "data_saida" date default null,
  primary key ("id")
)
engine InnoDB
default charset latin1;
drop table if exists "planilha_paciente";
create table "planilha_paciente" (
  "id" bigint not null generated by default as identity,
  "bairro" varchar(64) default null,
  "cep" varchar(16) default null,
  "cidade" varchar(64) default null,
  "codigo" varchar(16) default null,
  "cpf" varchar(16) default null,
  "dataCadastro" date default null,
  "dataNascimento" date default null,
  "endereco" varchar(64) default null,
  "estadoCivil" varchar(32) default null,
  "nacionalidade" varchar(64) default null,
  "naturalidade" varchar(64) default null,
  "nome" varchar(64) default null,
  "numero" varchar(16) default null,
  "profissao" varchar(64) default null,
  "rg" varchar(32) default null,
  "sobrenome" varchar(64) default null,
  "telefone" varchar(32) default null,
  "telefone2" varchar(32) default null,
  "uf" varchar(64) default null,
  "data_cadastro" date default null,
  "data_nascimento" date default null,
  "estado_civil" varchar(32) default null,
  primary key ("id")
)
engine InnoDB
default charset latin1;
drop table if exists "quarto";
create table "quarto" (
  "id" bigint not null generated by default as identity,
  "ativo" varchar(1) default null,
  "descricao" varchar(255) not null,
  "numero" int not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "quarto_un01"
    unique ("numero"),
  constraint "quarto_un02"
    unique ("descricao")
)
engine InnoDB
auto_increment 13
default charset latin1;
drop table if exists "quarto_destinacoes";
create table "quarto_destinacoes" (
  "quarto_id" bigint not null,
  "destinacao_hospedagem_id" bigint not null,
  primary key ("quarto_id", "destinacao_hospedagem_id")
)
engine InnoDB
default charset latin1;
drop table if exists "roles";
create table "roles" (
  "id" bigint not null generated by default as identity,
  "name" varchar(64) default null,
  primary key ("id"),
  constraint "UK_nb4h0p6txrmfc0xbrd1kglp9t"
    unique ("name")
)
engine InnoDB
auto_increment 5
default charset latin1;
drop table if exists "tipo_hospede";
create table "tipo_hospede" (
  "id" bigint not null generated by default as identity,
  "descricao" varchar(32) default null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "tipo_hospede_un01"
    unique ("descricao")
)
engine InnoDB
auto_increment 4
default charset latin1;
drop table if exists "tipo_leito";
create table "tipo_leito" (
  "id" bigint not null generated by default as identity,
  "descricao" varchar(32) not null,
  "quantidade_camas" int not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "tipo_leito_un01"
    unique ("descricao")
)
engine InnoDB
auto_increment 4
default charset latin1;
drop table if exists "tipo_servico";
create table "tipo_servico" (
  "id" bigint not null generated by default as identity,
  "ativo" varchar(1) not null,
  "descricao" varchar(32) not null,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "created_by" bigint default null,
  "updated_by" bigint default null,
  primary key ("id"),
  constraint "tipo_servico_un01"
    unique ("descricao")
)
engine InnoDB
auto_increment 8
default charset latin1;
drop table if exists "user_roles";
create table "user_roles" (
  "user_id" bigint not null,
  "role_id" bigint not null,
  primary key ("user_id", "role_id"))
engine InnoDB
default charset latin1;
drop table if exists "user_token";
create table "user_token" (
  "id" bigint not null generated by default as identity,
  "ativo" varchar(1) default null,
  "data_hora_criacao" timestamp not null,
  "data_hora_validade" timestamp not null,
  "email" varchar(255) default null,
  "token" varchar(64) default null,
  primary key ("id")
)
engine InnoDB
auto_increment 10
default charset latin1;
drop table if exists "users";
create table "users" (
  "id" bigint not null generated by default as identity,
  "created_at" timestamp default null,
  "updated_at" timestamp default null,
  "email" varchar(64) default null,
  "name" varchar(64) default null,
  "password" varchar(128) default null,
  "username" varchar(32) default null,
  primary key ("id"),
  constraint "UKr43af9ap4edm43mmtq01oddj6"
    unique ("username"),
  constraint "UK6dotkott2kjsp8vw4d0m25fb7"
    unique ("email")
)
engine InnoDB
auto_increment 12
default charset latin1;